### ISSUE TITLE
efo_otar_slim.owl generation

### ISSUE THREAD

**Issue by zoependlington** [EBISPOT/efo#1180]
When running the OTAR slim pipeline for the 3.32.0 release (July), the pipeline failed when generating the efo_otar_slim.owl file. This hasn’t been an issue before now at all but it seems like filtering for descendants is causing the file not to be created.

The line of code generating the file:

`robot filter --input efo_otar_profile.owl -T ./templates/allTAs.txt --select "annotations self descendants"  merge -i obsoletes.owl -o efo_otar_slim.owl`

This is the error:
```
Exception in thread "main" java.lang.StackOverflowError
	at uk.ac.manchester.cs.owl.owlapi.OWLImmutableOntologyImpl.getAxioms(OWLImmutableOntologyImpl.java:1323)
	at uk.ac.manchester.cs.owl.owlapi.OWLAxiomIndexImpl.getSubClassAxiomsForSuperClass(OWLAxiomIndexImpl.java:142)
	at uk.ac.manchester.cs.owl.owlapi.concurrent.ConcurrentOWLOntologyImpl.getSubClassAxiomsForSuperClass(ConcurrentOWLOntologyImpl.java:1779)
	at org.semanticweb.owlapi.search.EntitySearcher.getSubClasses(EntitySearcher.java:839)
	at org.obolibrary.robot.RelatedObjectsHelper.selectClassDescendants(RelatedObjectsHelper.java:1939)
	at org.obolibrary.robot.RelatedObjectsHelper.selectClassDescendants(RelatedObjectsHelper.java:1944)
```

**Comment by tskir** [comment]
@zoependlington 

Hi Zoe! I was wondering if you could provide me with a timeline for when this issue will be addressed? I'm afraid having the OTAR slim file is critical for many Open Targets operations, including most importantly the processing of the upcoming release

**Comment by zoependlington** [comment]
@tskir

The aim is to have the slim file attached to the August release - I am still working on figuring out the issue. For now, our June version of the slim file is still available to be used here: https://github.com/EBISPOT/efo/releases/tag/v3.31.0

**Comment by zoependlington** [comment]
@matentzn Would you be able to help look into/advise on this issue with ROBOT, please? Thanks!

**Comment by matentzn** [comment]
maybe you need to add more memory to ROBOT.

```
export ROBOT_JAVA_ARGS='-Xmx10G'
robot filter --input efo_otar_profile.owl -T ./templates/allTAs.txt --select "annotations self descendants"  merge -i obsoletes.owl -o efo_otar_slim.owl
```

**Comment by tskir** [comment]
Hi @zoependlington @matentzn, sorry to bother you, but did you have a chance to look into this? Is the file still expected for the August release?

**Comment by zoependlington** [comment]
Hi @tskir, yes, we have found the issue and rectified it so the slim file will be attached to the August release.
